application: moyskladtelegrambot
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: bot_gae.app

libraries:
- name: jinja2
  version: "2.6"
- name: ssl
  version: latest

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'anyvalue'